### ISSUE TITLE
Moderation Tool

### ISSUE THREAD

**Issue by hkrishna** [pelias/feedback#17]
Build a tool that lets the user save/discard/edit test cases populated by the feedback app. Basically, this will talk to mongodb, retrieve unmoderated documents and lets an admin edit and/or mark said document as moderated. 

Maybe have a github login auth and a whitelist of users that are admins or do it at ops level - expose the link with a username/password to your admins.

**Comment by sevko** [comment]
I think this is fairly low priority since I'll be manually moderating the exported-tests PRs for the near future.
