### ISSUE TITLE
Record User Location with Feedback

### ISSUE THREAD

**Issue by kevinkreiser** [pelias/feedback#19]
It might be helpful to know a given user's location in conjuction with what they thought was the most appropriate result in a list of results. Sometimes this won't be useful. like when they are searching for things not near by them. But it might help you to not artificially inflate the score of a result that was only important to a specific user simply because its the best match closest to them.

**Comment by hkrishna** [comment]
Yeah, this is true. Thanks for opening up this issue. Hopefully, we get to it soon but recording user location with feedback is something on the roadmap for sure.
