### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by hkrishna** [pelias/feedback#9]
![screen shot 2015-03-13 at 3 28 36 pm](https://cloud.githubusercontent.com/assets/840737/6648318/af253556-c995-11e4-8969-86eadba3d303.png)

Clicking on the map marker for the first time creates a thin popup bubble. When you click on the map marker again, it resets itself to the correct width

![screen shot 2015-03-13 at 3 29 29 pm](https://cloud.githubusercontent.com/assets/840737/6648337/c9157340-c995-11e4-8218-b98fc9987209.png)

**Comment by hanbyul-here** [comment]
can’t figure out why it is not picking up the content’s width only for first time =( but

style.css

```
.key-row{
white-space: nowrap;
}
.leaflet-popup-content{
width: auto !important;
}
```

script.js

```
var add_marker = function(geo, text) {
...
for (key in text){
full_text += ('<div class="key-row"><span class=\'key\'>' + key + '</span>: ' + text[key] + '</div>');
}
… 
}
```

This can be quick fix for the problem.

**Comment by hkrishna** [comment]
Thanks @hanbyul-here - that could work. Did you get it to work locally?  If so, can make a pull request?? :smile_cat:

**Comment by hanbyul-here** [comment]
I think leaflet style was getting confused because of 'hidden' style. I used width:0 instead of hiding map now it seems to work right.

**Comment by hanbyul-here** [comment]
buut also, how about not hiding map at all? I didn't notice that there is additional map function actually.. :>

**Comment by hkrishna** [comment]
closing this in favor of https://github.com/pelias/feedback/issues/14
